import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { RepoInfo } from "./repo-detector.js";
import { getPRStrategy } from "./strategies/index.js";

// Re-export for backwards compatibility and testing
export { escapeShellArg } from "./shell-utils.js";

export interface FileAction {
  fileName: string;
  action: "create" | "update";
}

export interface PROptions {
  repoInfo: RepoInfo;
  branchName: string;
  baseBranch: string;
  files: FileAction[];
  workDir: string;
  dryRun?: boolean;
  /** Number of retries for API operations (default: 3) */
  retries?: number;
}

export interface PRResult {
  url?: string;
  success: boolean;
  message: string;
}

function loadPRTemplate(): string {
  // Try to find PR.md in the project root
  const __filename = fileURLToPath(import.meta.url);
  const __dirname = dirname(__filename);
  const templatePath = join(__dirname, "..", "PR.md");

  if (existsSync(templatePath)) {
    return readFileSync(templatePath, "utf-8");
  }

  // Fallback template for multi-file support
  return `## Summary
Automated sync of configuration files.

## Changes
{{FILE_CHANGES}}

## Source
Configuration synced using [json-config-sync](https://github.com/anthony-spruyt/json-config-sync).

---
_This PR was automatically generated by [json-config-sync](https://github.com/anthony-spruyt/json-config-sync)_`;
}

/**
 * Format PR body for multiple files
 */
export function formatPRBody(files: FileAction[]): string {
  const template = loadPRTemplate();

  // Check if template supports multi-file format
  if (template.includes("{{FILE_CHANGES}}")) {
    // Multi-file template
    const fileChanges = files
      .map((f) => {
        const actionText = f.action === "create" ? "Created" : "Updated";
        return `- ${actionText} \`${f.fileName}\``;
      })
      .join("\n");

    return template.replace(/\{\{FILE_CHANGES\}\}/g, fileChanges);
  }

  // Legacy single-file template - adapt it for multiple files
  if (files.length === 1) {
    const actionText = files[0].action === "create" ? "Created" : "Updated";
    return template
      .replace(/\{\{FILE_NAME\}\}/g, files[0].fileName)
      .replace(/\{\{ACTION\}\}/g, actionText);
  }

  // Multiple files with legacy template - generate custom body
  const fileChanges = files
    .map((f) => {
      const actionText = f.action === "create" ? "Created" : "Updated";
      return `- ${actionText} \`${f.fileName}\``;
    })
    .join("\n");

  return `## Summary
Automated sync of configuration files.

## Changes
${fileChanges}

## Source
Configuration synced using [json-config-sync](https://github.com/anthony-spruyt/json-config-sync).

---
_This PR was automatically generated by [json-config-sync](https://github.com/anthony-spruyt/json-config-sync)_`;
}

/**
 * Generate PR title based on files changed
 */
export function formatPRTitle(files: FileAction[]): string {
  if (files.length === 1) {
    return `chore: sync ${files[0].fileName}`;
  }

  if (files.length <= 3) {
    const fileNames = files.map((f) => f.fileName).join(", ");
    return `chore: sync ${fileNames}`;
  }

  return `chore: sync ${files.length} config files`;
}

export async function createPR(options: PROptions): Promise<PRResult> {
  const { repoInfo, branchName, baseBranch, files, workDir, dryRun, retries } =
    options;

  const title = formatPRTitle(files);
  const body = formatPRBody(files);

  if (dryRun) {
    return {
      success: true,
      message: `[DRY RUN] Would create PR: "${title}"`,
    };
  }

  // Get the appropriate strategy and execute
  const strategy = getPRStrategy(repoInfo);
  return strategy.execute({
    repoInfo,
    title,
    body,
    branchName,
    baseBranch,
    workDir,
    retries,
  });
}
